### ISSUE TITLE
Polling logic should be smarter about creating the recordset to avoid API spamming

### ISSUE THREAD

**Issue by aurcioli-handy** [wearemolecule/route53-kubernetes#41]
https://github.com/wearemolecule/route53-kubernetes/blob/master/service_listener.go#L116

Currently the logic in the loop does not detect if the recordset for the ELB has already been created, causing the Go code to continuously make the `ChangeResourceRecordSets` API call to AWS. 

The script should detect if the correct recordset exists before making the call.

**Comment by FrederikNJS** [comment]
We are running into issues with route53 being rate-limited due to this project eating up all the quota.

The error message from AWS is "Rate for operation ChangeResourceRecordSets exceeded"

From the log, I can see that route53-kubernetes recreates all of the DNS records every 30 seconds, so that's a lot of API requests.

**Comment by aurcioli-handy** [comment]
I've submitted a PR for this could use a pair of eyes, I have yet to test end to end:
https://github.com/wearemolecule/route53-kubernetes/pull/44
